AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy Docker container from Docker Hub on EC2

Resources:
  WebAppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP and SSH
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  WebAppInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0b05d988257befbbe  # Ubuntu 22.04 in us-east-2
      KeyName: harsha-key             # Replace with your EC2 key pair
      SecurityGroupIds:
        - !Ref WebAppSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          apt update -y
          apt install -y docker.io
          systemctl start docker
          systemctl enable docker
          docker pull harsha10200/harsha-web:latest
          docker run -d -p 80:3000 harsha102001/harsha-web:latest
